name: Generate documentation

on:
  push:
    branches:
      - development

jobs:
  documentation:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone repository
        run: npm ci && npm run compodoc:generate
      - name: Push documentation
        run: |
          git add .
          git commit -m "docs: update documentation"
