name: Generate documentation

on:
  push:
    branches:
      - development

jobs:
  documentation:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone repository
        run: npm ci && npm run compodoc:generate
      - name: Push documentation
        run: |
          git config --global user.email "<${{ github.actor }}@users.noreply.github.com>"
          git config --global user.name "${{ github.actor }}"
          git add .
          git commit -m "docs: update documentation"
          git push origin documentation
